CREATE TABLE GAMES (
    GAME_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    LAST_DRAW INTEGER NOT NULL,
    NEXT_DRAW INTEGER NOT NULL,
    DATE_LAST_DRAW DATE NOT NULL,
    DATE_NEXT_DRAW DATE NOT NULL,
    NUMBER_MIN INTEGER NOT NULL,
    NUMBER_MAX INTEGER NOT NULL,
    DATE_UPDATE DATE DEFAULT CURRENT_DATE NOT NULL
);

/

CREATE TABLE GAME_DRAW (
    GAME_DRAW_ID SERIAL PRIMARY KEY,
    GAME_ID INTEGER REFERENCES GAMES(GAME_ID) NOT NULL,
    DRAW INTEGER NOT NULL,
    DATE_DRAW DATE NOT NULL,
    SCORES TEXT NOT NULL,
    DATE_UPDATE DATE DEFAULT CURRENT_DATE NOT NULL
);

/

CREATE TABLE GAME_STATISTICAL (
    GAME_STATISTICAL_ID SERIAL PRIMARY KEY,
    GAME_ID INTEGER REFERENCES GAMES(GAME_ID) NOT NULL,    
    STATISTICAL TEXT NOT NULL,
    DATE_UPDATE DATE DEFAULT CURRENT_DATE NOT NULL
);